### ISSUE TITLE
Weapon error 

### ISSUE THREAD

**Issue by AyPiXt** [dojwun/qb-weapons#4]
I get this error from the wweapon script but i think it have something to do with the inventory   i use your inventory here. 
Also thorwable weapons dsoent work cuz they are not added only the snowball is working but its just a self add i think. 
Nice work on the inventory and weapons btw 
![image](https://user-images.githubusercontent.com/76070305/139727384-d69f697b-a716-43a6-b624-3f542969ae9e.png)

**Comment by dojwun** [comment]
Thank you for the feed back man much apricated!, i will give this a look over & will also add more throwables
